# Numpy

In [2]:
import numpy as np

In [3]:
# 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally
A = np.array([1,2,3])
B = np.array([4,5,6])

# Vertical stacking
vert_stack = np.vstack((A,B))
print("Vertical stacking of A and B: ")
print(vert_stack)

# Horizontal stacking
hori_stack = np.hstack((A,B))
print("Horizontal stacking of A and B: ")
print(hori_stack)

Vertical stacking of A and B: 
[[1 2 3]
 [4 5 6]]
Horizontal stacking of A and B: 
[1 2 3 4 5 6]


In [4]:
# 2. Find common elements between A and B. [Hint: Intersection of two sets]
A = np.array([1,2,3,4,5])
B = np.array([3,4,5,6,7])
common = np.intersect1d(A,B)
print("Common elements between A and B: ", common)

Common elements between A and B:  [3 4 5]


In [7]:
# 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
A = np.array([2, 5, 7, 10, 12, 9, 4])
print("A: ", A)

'''
(A >= 5) → [False, True, True, True, True, True, False]
(A <= 10) → [ True, True, True, True, False, True, True]
Combine both with & → only elements between 5 and 10 (inclusive) remain.
'''
result = A[(A >= 5) & (A <= 10)]
print("All numbers from A that are between 5 and 10: ", result)

A:  [ 2  5  7 10 12  9  4]
All numbers from A that are between 5 and 10:  [ 5  7 10  9]


In [8]:
# 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# print(iris_2d)

#  Filter the rows of iris_2d that has petallength (3rd column) > 1.5
filtered1 = iris_2d[iris_2d[:,2] > 1.5]
print("The rows of iris_2d that has petallength (3rd column) > 1.5: ")
print(filtered1)

The rows of iris_2d that has petallength (3rd column) > 1.5: 
[[5.4 3.9 1.7 0.4]
 [4.8 3.4 1.6 0.2]
 [5.7 3.8 1.7 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [5.1 3.8 1.6 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3

In [9]:
# Filter the rows of iris_2d that has sepallength (1st column) < 5.0
filtered2 = iris_2d[iris_2d[:,0] < 5.0]
print("The rows of iris_2d that has sepallength (1st column) < 5.0: ")
print(filtered2)

The rows of iris_2d that has sepallength (1st column) < 5.0: 
[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [4.6 3.6 1.  0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [4.8 3.  1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


# Pandas

In [10]:
import pandas as pd

In [11]:
# 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

subset = ["Manufacturer", "Model", "Type"]
sample = df.loc[df.index % 20 == 0, subset]

print("Filtered the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0) from the dataframe:")
print(sample)

Filtered the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0) from the dataframe:
   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [12]:
# 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# Get the mean of Min.Price and Max.Price columns
min_price_mean = df["Min.Price"].mean()
max_price_mean = df["Max.Price"].mean()

# Fill NaN values in Min.Price and Max.Price columns with their respective mean using fillna function
df["Max.Price"] = df["Max.Price"].fillna(max_price_mean)
df["Min.Price"] = df["Min.Price"].fillna(min_price_mean)

print("Dataframe after replacing missing values in Min.Price and Max.Price columns with their respective mean:")
print(df)


Dataframe after replacing missing values in Min.Price and Max.Price columns with their respective mean:
   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.5000

In [13]:
# 3. How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
filtered = df[df.sum(axis=1) > 100]
print("The rows of the dataframe with row sum > 100 are the following: ")
print(filtered)

The rows of the dataframe with row sum > 100 are the following: 
     0   1   2   3
1   17  21  30  38
2   27  23  15  37
4   28  20  26  32
5   20  22  39  36
6   31  23  37  25
9   18  16  35  32
13  27  20  35  26
14  35  26  22  25
